name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ============================================================================
  # Build and Test on Linux
  # ============================================================================
  build-linux:
    strategy:
      matrix:
        node: [20.x, 22.x, 24.x]
        os: [ubuntu-24.04, ubuntu-24.04-arm]

    name: Node ${{ matrix.node }} [${{ matrix.os }}]

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ matrix.node }}

      - name: Build Library
        run: |
          npm clean-install --ignore-scripts
          ./build.sh

        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
          PGTESTNOSSL: true
          PGUSER: postgres
          PGHOST: localhost
          PGPASSWORD: postgres
          PGDATABASE: ci_db_test

  # ============================================================================
  # Build and Test on MacOS
  # ============================================================================
  build-macos:
    strategy:
      matrix:
        node: [20.x, 22.x, 24.x]
        os: [macos-15, macos-15-intel]

    name: Node ${{ matrix.node }} [${{ matrix.os }}]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: ${{ matrix.node }}

      - name: Build Library
        run: |
          npm clean-install --ignore-scripts
          ./build.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
